extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  zipkin:

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024        

exporters:
  logging:
    loglevel: info
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true    
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: default
    
service:
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      processors: [batch]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
  telemetry:
    logs:
      level: info
  extensions:
    - health_check
    - zpages
