receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  logging:
    loglevel: info
  awsemf:
    region: 'ap-southeast-2'
    log_group_name: '/metrics/otel'
    log_stream_name: 'otel'
  awsxray:
    region: 'ap-southeast-2'

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, awsemf]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, awsxray]
