global:
  evaluation_interval: 30s
  scrape_interval: 15s
scrape_configs:
- job_name: otel
  static_configs:
  - targets:
    - 'collector:8889'
- job_name: collector
  static_configs:
  - targets:
    - 'collector:8888'
