version: '3.0'

services:

  otel-n-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: otel-n-test:latest
    container_name: otel-n-test
    hostname: otel-n-test
#    depends_on:
#      - collector
    ports:
      - "1113:1113"
    env_file:
      - otel-agent.env
    environment: 
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=otel-n-testtest,service.version=1.0,deployment.environment=development
      - OTEL_LOG_LEVEL=debug
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - AWS_PROFILE=default
      - AWS_REGION=ap-southeast-2
      - INSTANCE_ID
      - LISTEN_ADDRESS=0.0.0.0:1113

networks:
  default:
    name: m2m
    external: true
