version: '3.0'

services:

  otel-j-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: otel-j-app:latest
    container_name: otel-j-app
    hostname: otel-j-app
#    depends_on:
#      - collector
    ports:
      - "1111:1111"
    env_file:
      - otel-agent.env
    environment:
      - OTEL_SERVICE_NAME=otel-j-app
    volumes:
      - ./otel.properties:/otel.properties
    healthcheck:
      interval: 5s
      retries: 10
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:1111/hello || exit 1

networks:
  default:
    name: m2m
    external: true
