version: '3.0'

services:

  otel-n-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: otel-n-app:latest
    container_name: otel-n-app
    hostname: otel-n-app
#    depends_on:
#      - collector
    ports:
      - "1112:1112"
    env_file:
      - otel-agent.env
    environment:
      - OTEL_SERVICE_NAME=otel-n-app
    healthcheck:
      interval: 5s
      retries: 10
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:1112/hello || exit 1

networks:
  default:
    name: m2m
    external: true
